name: Network Security CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

  pull_request:
    branches:
      - main

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Check Python Syntax
        run: |
          python -m compileall .

      - name: Install Ruff Linter
        run: |
          pip install ruff

      - name: Run Ruff Linter
        run: |
          ruff check .

      - name: Build Docker Image
        run: |
          docker build -t network-security .

      - name: CI Completed
        run: echo "✅ Continuous Integration completed successfully!"

  build-and-push-ecr-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_NAME }} .

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:latest \
          ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest

      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest

      - name: CD Completed
        run: echo "✅ Docker Image pushed to Amazon ECR successfully!"

  deploy-to-ec2:
    name: Deploy To EC2
    needs: build-and-push-ecr-image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_LOGIN_URI }}

            docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest

            docker stop network-security || true

            docker rm network-security || true

            docker run -d \
              --name network-security \
              -p 8000:8000 \
              ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest